stages:
  - install
  - test
  - sast
  - build
  - deploy_local
  - terraform_plan

default:
  tags:
    - local

variables:
  APP_NAME: "secnotes"
  IMAGE_TAG: "$CI_COMMIT_SHORT_SHA"
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"

cache:
  paths:
    - node_modules/
    - .sonar/cache/

install_dependencies:
  stage: install
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 day

run_tests:
  stage: test
  dependencies:
    - install_dependencies
  script:
    - npm test

sonar_scan:
  stage: test
  script:
    - $env:JAVA_HOME="C:\Program Files\Eclipse Adoptium\jdk-17.0.18.8-hotspot"
    - $env:Path="$env:JAVA_HOME\bin;$env:Path"
    - java -version
    - powershell -ExecutionPolicy Bypass -File "C:\Users\pc\AppData\Roaming\npm\sonar-scanner.ps1" "-Dsonar.host.url=http://localhost:9000" "-Dsonar.login=$($env:SONAR_TOKEN)" "-Dsonar.projectKey=secnotes-vuln-app"
    
docker_build:
  stage: build
  script:
    - docker build -t secnotes:$IMAGE_TAG .
    - docker tag secnotes:$IMAGE_TAG secnotes:latest

deploy_k8s_local:
  stage: deploy_local
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  script:
    - echo "Skipping K8s for now"

terraform_plan:
  stage: terraform_plan
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  when: manual
  script:
    - cd terraform
    - terraform init
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - terraform/tfplan
    expire_in: 1 day