apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: logviewer
type: Opaque
stringData:
  MONGO_USERNAME: admin
  MONGO_PASSWORD: changeme123  # change before any real deployment
  MONGO_URI: "mongodb://admin:changeme123@mongodb:27017/logviewer?authSource=admin"