apiVersion: v1
kind: Service
metadata:
  name: logviewer-svc
  namespace: logviewer
spec:
  type: NodePort
  selector:
    app: logviewer
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30300