apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upload-app
  template:
    metadata:
      labels:
        app: upload-app
    spec:
      containers:
        - name: upload-app
          image: kube:tag
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: NODE_ENV
              value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: upload-app-service
  namespace: default
spec:
  selector:
    app: upload-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer